#!/usr/bin/env python3
"""
search_political_keywords.py

Scans a directory of qualitative analysis reports (generated by
qualitative_analysis.py) to identify communities that use political keywords
above a certain frequency threshold.

This helps in creating a more robust shortlist of political echo chamber candidates.

Usage:
    python search_political_keywords.py \\
        --reports_dir /path/to/qualitative_reports \\
        --outfile /path/to/political_candidates.csv \\
        --keywords trump biden maga politics democrat republican \\
        --threshold 100
"""
import argparse
import pandas as pd
import os
import re

def main(args):
    """
    Main function to find political communities based on keywords and a count threshold.
    """
    if not os.path.isdir(args.reports_dir):
        print(f"Error: The specified reports directory does not exist: {args.reports_dir}")
        return

    print(f"Searching for political keywords in reports from: {args.reports_dir}")
    print(f"Keywords: {', '.join(args.keywords)}")
    print(f"Minimum total count threshold: {args.threshold}")

    # --- 1. Compile keywords into a case-insensitive regex pattern ---
    keyword_pattern = re.compile(r'|'.join(args.keywords), re.IGNORECASE)

    political_candidates = []
    
    # --- 2. Iterate through all report files in the directory ---
    report_files = [f for f in os.listdir(args.reports_dir) if f.endswith('.csv')]
    print(f"Found {len(report_files):,} report files to scan.")

    for i, filename in enumerate(report_files):
        if (i + 1) % 100 == 0:
            print(f"  > Scanned {i+1}/{len(report_files)} files...")
        
        try:
            # --- 3. Parse resolution and community ID from the filename ---
            parts = filename.replace('.csv', '').split('_')
            res = parts[1].replace('res', '')
            comm_id = parts[2].replace('comm', '')
            
            filepath = os.path.join(args.reports_dir, filename)
            df_report = pd.read_csv(filepath)

            if 'hashtag_text' not in df_report.columns or 'count' not in df_report.columns:
                continue

            # --- 4. Search for keywords and sum their counts ---
            hashtags = df_report['hashtag_text'].dropna().astype(str)
            
            # Create a boolean mask for rows containing any of the keywords
            mask = hashtags.str.contains(keyword_pattern)
            
            if mask.any():
                # Sum the 'count' column for only the rows that match the keywords
                political_hashtag_count = df_report.loc[mask, 'count'].sum()
                
                # Check if this total count meets the specified threshold
                if political_hashtag_count >= args.threshold:
                    print(f"  > Found political community: {filename} (Total count: {political_hashtag_count})")
                    political_candidates.append({
                        'resolution': res,
                        'community_id': comm_id,
                        'political_hashtag_count': political_hashtag_count,
                        'filename': filename
                    })

        except (IndexError, pd.errors.EmptyDataError):
            print(f"  > Warning: Could not parse or read file: {filename}. Skipping.")
            continue

    # --- 5. Save the results ---
    if not political_candidates:
        print("\nNo communities meeting the political keyword threshold were found.")
        return

    df_political = pd.DataFrame(political_candidates)
    # Sort by the intensity of political conversation first, then by resolution
    df_political = df_political.sort_values(by=['political_hashtag_count', 'resolution'], ascending=[False, True])
    
    df_political.to_csv(args.outfile, index=False)
    
    print(f"\n✅ Successfully found {len(df_political)} political candidates.")
    print(f"Saved the list to: {args.outfile}")
    
    print("\n--- Top Political Candidates Found ---")
    print(df_political.head().to_string(index=False))
    print("--------------------------------------")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Identify political communities by searching for keywords in hashtag reports.")
    parser.add_argument('--reports_dir', required=True, help='Directory containing the CSV reports from qualitative_analysis.py.')
    parser.add_argument('--outfile', required=True, help='Path to save the output CSV of political candidates.')
    parser.add_argument('--keywords', nargs='+', required=True, help='A list of political keywords to search for (e.g., trump biden maga).')
    parser.add_argument('--threshold', type=int, default=5000, help='Minimum total count of political hashtags for a community to be considered political.')
    args = parser.parse_args()

    main(args)

