name: Run Extraction Pipeline

on:
  push:
    branches:
      - 'exp/*'

env:
  PROP_FILE: 'prop.ipazia.yaml'
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  extract:
    timeout-minutes: 50000  # 34 days max time to run
    runs-on: self-hosted # Executes directly on your target server 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Podman Image
        run: |
          podman build \
            --build-arg CACHE_BUST=$(git rev-parse HEAD) \
            -t graph-analysis -f docker/Dockerfile .

      - name: Prepare Host Directories
        run: |
          mkdir -p ${{ vars.IPAZIA_WORK_DIR }}/extraction/outputs
          mkdir -p ${{ vars.IPAZIA_WORK_DIR }}/extraction/logs

      - name: Run Extraction Container
        run: |
          # Mount the selected configuration file into the container
          podman run --replace \
            --name graph_analysis \
            --network host \
            -v ${{ vars.IPAZIA_WORK_DIR }}/extraction/outputs:/app/resources \
            -v ${{ vars.IPAZIA_WORK_DIR }}/extraction/logs:/app/logs \
            -v "${{ github.workspace }}/properties/${{ env.PROP_FILE }}":/app/properties/prop.yaml:ro \
            -e MONGO_URI \
            -e MONGO_USERNAME \
            -e MONGO_PASSWORD \
            graph-analysis --properties /app/properties/prop.yaml
